on:
  push:
    branches: master
  schedule:
    - cron: '0 */12 * * *'
      
jobs:
  build:
    name: Update Readme.md
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Debris action
        uses: ekickx/debris@master 
        with:
          fact_args: 'random'
