on:
  push:
    branches: master
  schedule:
    - cron: '30 17 * * *'

jobs:
  build:
    name: Update Readme.md
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
